alpha: 0.3
dataset: Citeseer
embedding_size: 32
epoch: 25
hidden_sizes:
- 512
- 32
lr: 0.001
max_epoch: 100
n_clusters: 6
num_gat_layers: 2
num_heads: 2
pre_lr: 0.01
update_interval: 1
weight_decay: 1E-8
dropout : 0.2
